version: "3.5"

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: private
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    command: mongod --port 27017 --auth
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: private
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
      
  todo-api:
    image: lufiaraujo/todo-api:1.0
    ports:
      - 3001:3001
    environment:
      DB_SERVER: mongodb://admin:private@mongo/
    depends_on:
      - mongo

  todo-app:
    image: lufiaraujo/todo-app:1.0
    ports:
      - 3000:3000
    environment:
      API_SERVER: http://todo-api:3001/
    depends_on:
      - todo-api

volumes:
  db-data:
    driver: local